### ISSUE TITLE
API

### ISSUE THREAD

**Issue by MasterCodeIT** [Xplatforms/mbseedkey#14]
Not an issue but I am working on a project and when the ecu responds with the security seed request I want it to auto-generate the "seedkey". Possible to implement this in a simple api format?

**Comment by Xplatforms** [comment]
Sure,  there is ECUSeedKeyDLL  class which could be used for that

**Comment by MasterCodeIT** [comment]
Pick your brain for a moment?

Having a bit of trouble getting it to work. Project is built on python. I have the DLL for the ECUs.

Attempting to simplify the path via python. 

**Example:**

dll_file = "ecu_file_name.dll"
access_level = "05"
seed = "ecu seed response"
ecuKey = ECUSeedKeyDLL(seed)
send ecukey

**Comment by Xplatforms** [comment]
I can add command line args like "mbseedkey.exe -dll <path to dll> -acc <access level> -seed <SEED>" if you wish. It will then print generated key to stdout. So you can execute it from python and read response key from stdout

**Comment by MasterCodeIT** [comment]
> 
> 
> I can add command line args like "mbseedkey.exe -dll -acc -seed " if you wish. It will then print generated key to stdout. So you can execute it from python and read response key from stdout

That would be good. Could you do that?

I only work on 3 specific ECU's, no way to integrate the keygen into my python project?
