### ISSUE TITLE
 ISG48V1 DLL is for CEPC253 ECU instead of ISG48V1 ECU

### ISSUE THREAD

**Issue by iPzard** [Xplatforms/mbseedkey#25]
Amazing app, happy to contribute if needed. Running into an issue generating a key for my starter alternator module. I am using the latest version available (as of today - 10/20/24). 

Issue: 
ECU name for ISG48v1 seed is actually CEPC253 and keys are invalid when used.

![image](https://github.com/user-attachments/assets/da3ad995-11c2-480a-930f-0976a6801c74)

Expected:
ECU name should match ECU seed key is being generated for. 
Generated seed with access of 0B should be valid for 0B level security related variant coding on ISG48v1

**Comment by iPzard** [comment]
Ok, got it _(attached)_

![image](https://github.com/user-attachments/assets/f8438661-7172-4933-8ec1-f429c7c95aa4)


[ISG48V1_IGS48V1_16_20_01.zip](https://github.com/user-attachments/files/17452743/ISG48V1_IGS48V1_16_20_01.zip)

**Comment by Xplatforms** [comment]
Hi @iPzard, thanks for reporting! Was it a GUI glitch (not switching to the correct DLL after selection), or was there an issue with the DLL itself?

**Comment by iPzard** [comment]
Unless I mixed it up at some point, the DLL itself was bad. Just in case, I attached the good one that worked for me in my last reply.
